# Generated by Django 4.1.6 on 2023-05-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
