# Generated by Django 4.1.6 on 2023-04-28 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "img",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                ("body", models.TextField()),
                (
                    "img2",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                (
                    "img3",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                ("body2", models.TextField(blank=True, default=None, null=True)),
                (
                    "audio",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="images"
                    ),
                ),
                ("writer", models.CharField(default=None, max_length=100)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_votes",
                        to="blog.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_post_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(max_length=300)),
                (
                    "name",
                    models.CharField(
                        blank=True, default="anonymous", max_length=100, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default=None, max_length=254, null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("is_reply", models.BooleanField(default=False)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comments",
                        to="blog.post",
                    ),
                ),
                (
                    "reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_replies",
                        to="blog.postcomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
