# Generated by Django 5.0.6 on 2024-06-21 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="created",
        ),
        migrations.AddField(
            model_name="message",
            name="email",
            field=models.EmailField(
                blank=True, default="Enter Your Email ...", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(default="Enter Your Message ...", null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="name",
            field=models.CharField(
                blank=True,
                default="Enter Your First & Last name ...",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="phone",
            field=models.CharField(
                blank=True,
                default="Enter Your Phone Number ...",
                max_length=17,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Example: +9121234567", regex="^\\+?98?\\d{9,15}$"
                    )
                ],
            ),
        ),
    ]
