# Generated by Django 5.0.6 on 2024-06-21 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_message_created_message_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="email",
        ),
        migrations.RemoveField(
            model_name="message",
            name="name",
        ),
        migrations.RemoveField(
            model_name="message",
            name="phone",
        ),
        migrations.AddField(
            model_name="message",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_cart",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
