# Generated by Django 5.0.6 on 2024-06-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_remove_message_email_remove_message_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
