# Generated by Django 5.0.6 on 2024-06-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_message_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="message",
            field=models.TextField(default="...Enter Your Message ...", null=True),
        ),
    ]
