# Generated by Django 4.1.6 on 2023-04-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(blank=True, default="M", max_length=10, null=True),
        ),
    ]
