# Generated by Django 4.1.6 on 2023-04-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_cartitem_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="discount",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
