# Generated by Django 4.1.6 on 2023-04-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_subscribe"),
    ]

    operations = [
        migrations.DeleteModel(name="Subscribe",),
    ]
