# Generated by Django 4.1.6 on 2023-05-05 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0007_seller_sellet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seller", old_name="sellet", new_name="seller",
        ),
    ]
