# Generated by Django 5.0.6 on 2024-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_promo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="short_desc",
            field=models.CharField(
                blank=True, default="See More", max_length=200, null=True
            ),
        ),
    ]
