# Generated by Django 5.0.6 on 2024-06-19 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0010_product_short_desc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_L",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_M",
        ),
        migrations.RemoveField(
            model_name="product",
            name="size_S",
        ),
    ]
