# Generated by Django 5.0.6 on 2024-06-19 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0011_remove_product_size_l_remove_product_size_m_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="hot",
        ),
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sale",
        ),
        migrations.RemoveField(
            model_name="product",
            name="shipping_tax",
        ),
    ]
