# Generated by Django 5.0.6 on 2024-06-19 15:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0012_remove_product_code_remove_product_hot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="shipping",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Promo",
        ),
        migrations.RemoveField(
            model_name="seller",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shipping",
            name="user",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="product",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
        migrations.DeleteModel(
            name="Shipping",
        ),
        migrations.DeleteModel(
            name="Vote",
        ),
    ]
