# Generated by Django 5.0.6 on 2024-06-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0013_remove_cart_customer_remove_cartitem_cart_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, default="Project", max_length=100, null=True
                    ),
                ),
                ("description", models.TextField()),
                (
                    "employee",
                    models.CharField(
                        blank=True, default="IUST", max_length=100, null=True
                    ),
                ),
                ("img_proj", models.FileField(default=None, upload_to="images")),
                ("img_emp", models.FileField(default=None, upload_to="images")),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
